name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java environment
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21' # Use Java 21
          distribution: 'corretto'

      # Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle

      # Build the project
      - name: Build with Gradle
        run: ./gradlew clean build -x test

      # Verify artifacts
      - name: Verify Build Artifacts
        run: ls -l build/libs/

      #Add VPS to known_hosts
      - name: Add VPS to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts

      # Copy JAR to VPS
      - name: Copy JAR to VPS
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: build/libs/valuation-service-0.0.1-SNAPSHOT.jar
          target: /opt/valuation/

      # Deploy to VPS
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Stop the existing service
            sudo systemctl stop valuation.service || true
      
            # Backup the existing JAR file
            if [ -f /opt/valuation/app.jar ]; then
            sudo mv /opt/valuation/app.jar /opt/valuation/app-$(date +%F-%T).jar
            fi
      
            # Rename the uploaded JAR to the standard name
            sudo mv /opt/valuation/valuation-service-0.0.1-SNAPSHOT.jar /opt/valuation/app.jar
      
            # Start the service
            sudo systemctl start valuation.service
